library(lubridate)
df<-read.table("household_power_consumption.txt",sep = ";",header = TRUE)
df$Date<-as.character(df$Date)
df$Date<-as.Date(df$Date,"%d/%m/%Y")
df<-subset(df,df$Date %in% as.Date(c("2007-02-01","2007-02-02")))
df$date_time<-paste(df$Date,df$Time)
df$date_time<-ymd_hms(df$date_time)
df$Global_active_power<-as.numeric(as.character(df$Global_active_power))
df$Sub_metering_1<-as.numeric(as.character(df$Sub_metering_1))
df$Sub_metering_2<-as.numeric(as.character(df$Sub_metering_2))
df$Sub_metering_3<-as.numeric(as.character(df$Sub_metering_3))
df$Global_reactive_power<-as.numeric(as.character(df$Global_reactive_power))
df$Voltage<-as.numeric(as.character(df$Voltage))
Sys.setlocale("LC_TIME", "English")
png(filename = "plot4.png",width = 480,height = 480)
par(mfrow=c(2,2))
plot(df$date_time,df$Global_active_power,type="l",ylab = "Global active power",xlab="")
plot(df$date_time,df$Voltage,type="l",xlab="datetime",ylab="Voltage")

with(df,plot(date_time,Sub_metering_1,type = "l",ylab = "Energy sub metering",xlab=""))
lines(df$date_time,df$Sub_metering_2,type="l",col="red")
lines(df$date_time,df$Sub_metering_3,type="l",col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),bty="n",lty=rep(1,3),cex=0.7 , col=c("black", "red", "blue"))
plot(df$date_time,df$Global_reactive_power,type="l",xlab ="datetime",ylab = "Global_reactive_power")
dev.off()