df<-read.table("household_power_consumption.txt",sep = ";",header = TRUE)
df$Date<-as.character(df$Date)
df$Date<-as.Date(df$Date,"%d/%m/%Y")
df<-subset(df,df$Date %in% as.Date(c("2007-02-01","2007-02-02")))
df$date_time<-paste(df$Date,df$Time)
df$date_time<-ymd_hms(df$date_time)
df$Sub_metering_1<-as.numeric(as.character(df$Sub_metering_1))
df$Sub_metering_2<-as.numeric(as.character(df$Sub_metering_2))
df$Sub_metering_3<-as.numeric(as.character(df$Sub_metering_3))
png(filename = "plot3.png",width = 480,height = 480)
with(df,plot(date_time,Sub_metering_1,type = "l",ylab = "Energy sub metering",xlab=""))
lines(df$date_time,df$Sub_metering_2,type="l",col="red")
lines(df$date_time,df$Sub_metering_3,type="l",col="blue")
legend("topright",lty=1,cex = 0.5,col=c("black","red","blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()
